### ISSUE TITLE
Fails to install from pip; UnicodeDecodeError

### ISSUE THREAD

**Issue by MikeS-nth** [Refinitiv-API-Samples/Article.OpenPermID.Python.APIs#1]
Installing from pip fails with a UnicodeDecodeError, due to an apparently incompatible character in the README file:

> $ pip install OpenPermID
> Collecting OpenPermID
>   Using cached https://files.pythonhosted.org/packages/4b/0c/afe4e71ee4c022d7bba3a3e0489e6a48902ac2c982e0639e4a01f2fb860b/OpenPermID-0.3.tar.gz
>     ERROR: Complete output from command python setup.py egg_info:
>     ERROR: Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/k6/fvmsww4d32j5d2fhznwtljyr0000gn/T/pip-install-s3gwfhyw/OpenPermID/setup.py", line 4, in <module>
>         long_description = f.read()
>       File "/Users/michaelsanders/anaconda3/envs/work/lib/python3.7/codecs.py", line 322, in decode
>         (result, consumed) = self._buffer_decode(data, self.errors, final)
>     UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 47: invalid start byte
>     ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k6/fvmsww4d32j5d2fhznwtljyr0000gn/T/pip-install-s3gwfhyw/OpenPermID/

The source of the error is this line in the README:
> PermID is a shortening of ìPermanent Identifier.î  

...specifically, the characters on either side of "Permanent Identifier".

This is solved by downloading the package, removing those characters from the REAME, and installing from src with `pip install <path>`

**Comment by jirapongse-refinitiv** [comment]
Thank you so much.

I have fixed it in 0.4.
